replicaCount: 1

image:
  repository: vishnukrajan007/emailservice
  tag: 5dff2c0
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5000
  targetPort: 8080

containerPort: 8080

resources:
  requests:
    cpu: 100m
    memory: 64Mi

  limits:
    cpu: 200m
    memory: 128Mi
