replicaCount: 1

image:
  repository: vishnukrajan007/recommendationservice
  tag: 5dff2c0
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

containerPort: 8080

resources:
  requests:
    cpu: 100m
    memory: 220Mi

  limits:
    cpu: 200m
    memory: 450Mi
