apiVersion: apps/v1
kind: Deployment

metadata:
  name: productcatalogservice

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: productcatalogservice

  template:
    metadata:
      labels:
        app: productcatalogservice

    spec:
      serviceAccountName: default
      terminationGracePeriodSeconds: 5

      containers:
        - name: server

          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - containerPort: {{ .Values.containerPort }}

          env:
            - name: PORT
              value: "3550"

            - name: DISABLE_PROFILER
              value: "1"

          resources:
{{ toYaml .Values.resources | indent 12 }}
