replicaCount: 1

image:
  repository: vishnukrajan007/loadgenerator
  tag: 5dff2c0
  pullPolicy: IfNotPresent

resources:
  requests:
    cpu: 300m
    memory: 256Mi

  limits:
    cpu: 500m
    memory: 512Mi
