apiVersion: apps/v1
kind: Deployment

metadata:
  name: redis-cart

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: redis-cart

  template:
    metadata:
      labels:
        app: redis-cart

    spec:
      containers:
        - name: redis

          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - containerPort: {{ .Values.containerPort }}

          volumeMounts:
            - name: redis-data
              mountPath: /data

          resources:
{{ toYaml .Values.resources | indent 12 }}

      volumes:
        - name: redis-data
          emptyDir: {}
