apiVersion: v1
kind: Service

metadata:
  name: redis-cart

spec:
  type: {{ .Values.service.type }}

  selector:
    app: redis-cart

  ports:
    - name: tcp-redis
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
