apiVersion: apps/v1
kind: Deployment

metadata:
  name: loadgenerator

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: loadgenerator

  template:
    metadata:
      labels:
        app: loadgenerator
      annotations:
        sidecar.istio.io/rewriteAppHTTPProbers: "true"

    spec:
      serviceAccountName: default
      terminationGracePeriodSeconds: 5
      restartPolicy: Always

      containers:
        - name: main

          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL

          env:
            - name: FRONTEND_ADDR
              value: "frontend:80"

            - name: USERS
              value: "10"

          resources:
{{ toYaml .Values.resources | indent 12 }}
