apiVersion: apps/v1
kind: Deployment

metadata:
  name: currencyservice

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: currencyservice

  template:
    metadata:
      labels:
        app: currencyservice

    spec:
      serviceAccountName: default
      terminationGracePeriodSeconds: 5

      containers:
        - name: server

          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - name: grpc
              containerPort: {{ .Values.containerPort }}

          env:
            - name: PORT
              value: "7000"

            - name: DISABLE_PROFILER
              value: "1"

          resources:
{{ toYaml .Values.resources | indent 12 }}
