apiVersion: apps/v1
kind: Deployment

metadata:
  name: adservice

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: adservice

  template:
    metadata:
      labels:
        app: adservice

    spec:
      serviceAccountName: default
      terminationGracePeriodSeconds: 5

      containers:
        - name: server

          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - containerPort: {{ .Values.containerPort }}

          env:
            - name: PORT
              value: "9555"

          readinessProbe:
            tcpSocket:
              port: 9555
            initialDelaySeconds: 5
            periodSeconds: 10
 
          livenessProbe:
            tcpSocket:
              port: 9555
            initialDelaySeconds: 10
            periodSeconds: 20
          

          resources:
{{ toYaml .Values.resources | indent 12 }}
