replicaCount: 1

image:
  repository: vishnukrajan007/currencyservice
  tag: 5dff2c0
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 7000
  targetPort: 7000

containerPort: 7000

resources:
  requests:
    cpu: 100m
    memory: 64Mi

  limits:
    cpu: 200m
    memory: 128Mi
