replicaCount: 1

image:
  repository: redis
  tag: alpine
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 6379
  targetPort: 6379

containerPort: 6379

resources:
  requests:
    cpu: 70m
    memory: 200Mi

  limits:
    cpu: 125m
    memory: 256Mi
